# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "zroot/safe/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    {
      device = "zroot/safe/home";
      fsType = "zfs";
    };

  fileSystems."/var/log" =
    {
      device = "zroot/safe/var/log";
      fsType = "zfs";
    };

  fileSystems."/var/log/journal" =
    {
      device = "zroot/safe/var/log/journal";
      fsType = "zfs";
    };

  fileSystems."/var/lib/AccountsService" =
    {
      device = "zroot/safe/var/lib/AccountsService";
      fsType = "zfs";
    };

  fileSystems."/var/lib/docker" =
    {
      device = "zroot/safe/var/lib/docker";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    {
      device = "zroot/local/nix";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/6018-3522";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/41088d46-9bc4-4c06-99e8-de67c257a304"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp42s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
